package com.tsingxin.dao;

import com.tsingxin.dataobject.CourseStockDO;
import org.apache.ibatis.annotations.Param;

public interface CourseStockDOMapper {

    CourseStockDO selectByCourseId(Integer courseId);

    int decreaseStock(@Param("courseId") Integer courseId, @Param("amount")Integer amount);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_stock
     *
     * @mbg.generated Thu Jun 11 15:49:38 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_stock
     *
     * @mbg.generated Thu Jun 11 15:49:38 CST 2020
     */
    int insert(CourseStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_stock
     *
     * @mbg.generated Thu Jun 11 15:49:38 CST 2020
     */
    int insertSelective(CourseStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_stock
     *
     * @mbg.generated Thu Jun 11 15:49:38 CST 2020
     */
    CourseStockDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_stock
     *
     * @mbg.generated Thu Jun 11 15:49:38 CST 2020
     */
    int updateByPrimaryKeySelective(CourseStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_stock
     *
     * @mbg.generated Thu Jun 11 15:49:38 CST 2020
     */
    int updateByPrimaryKey(CourseStockDO record);
}