package com.tsingxin.dao;

import com.tsingxin.dataobject.CourseDO;

import java.util.List;

public interface CourseDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Jun 11 15:49:38 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    List<CourseDO> listCourse();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Jun 11 15:49:38 CST 2020
     */
    int insert(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Jun 11 15:49:38 CST 2020
     */
    int insertSelective(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Jun 11 15:49:38 CST 2020
     */
    CourseDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Jun 11 15:49:38 CST 2020
     */
    int updateByPrimaryKeySelective(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Jun 11 15:49:38 CST 2020
     */
    int updateByPrimaryKey(CourseDO record);
}