package com.tsingxin.dao;

import com.tsingxin.dataobject.GrabDO;

public interface GrabDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grab
     *
     * @mbg.generated Thu Jun 11 15:49:38 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grab
     *
     * @mbg.generated Thu Jun 11 15:49:38 CST 2020
     */
    int insert(GrabDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grab
     *
     * @mbg.generated Thu Jun 11 15:49:38 CST 2020
     */
    int insertSelective(GrabDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grab
     *
     * @mbg.generated Thu Jun 11 15:49:38 CST 2020
     */
    GrabDO selectByPrimaryKey(Integer id);

    GrabDO selectByCourseId(Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grab
     *
     * @mbg.generated Thu Jun 11 15:49:38 CST 2020
     */
    int updateByPrimaryKeySelective(GrabDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grab
     *
     * @mbg.generated Thu Jun 11 15:49:38 CST 2020
     */
    int updateByPrimaryKey(GrabDO record);
}